// src/oceanpress-siyuan-plugin/ui/setting_view.tsx
import { createMemo, type Signal } from "solid-js";
import styles from "./setting_view.module.css";
import type { Dialog } from "siyuan";
export function setting_view(props: {
  dialog: Dialog;
  dataSignal: Signal<{ type: "oceanpress" | "umi-ocr"; sk: string; umiApi: string }>;
  save: () => void;
}) {
  const [data, set_data] = props.dataSignal;
  const selectedValue = createMemo(() => data().type);
  const sk = createMemo(() => data().sk);
  const umiApi = createMemo(() => data().umiApi);
  function onExit() {
    props.save();
    props.dialog.destroy();
  }
  return (
    <div class={styles.content}>
      选择 ocr api 提供程序：
      <select
        value={selectedValue()}
        onChange={(e) => set_data((prev) => ({ ...prev, type: e.target.value as "oceanpress" }))}
        name="ocr type">
        <option value="oceanpress">oceanpress</option>
        <option value="umi-ocr">umi-ocr</option>
      </select>
      {selectedValue() === "oceanpress" ? (
        <div>
          sk
          <input
            type="text"
            class={styles.input}
            placeholder="Enter sk..."
            value={sk()}
            onInput={(e) => set_data((prev) => ({ ...prev, sk: e.target.value }))}
          />
        </div>
      ) : null}
      {selectedValue() === "umi-ocr" ? (
        <div>
          http api
          <input
            type="text"
            class={styles.input}
            placeholder="Enter http api ..."
            value={umiApi()}
            onInput={(e) => set_data((prev) => ({ ...prev, umiApi: e.target.value }))}
          />
        </div>
      ) : null}
      <button class={styles.button} onClick={onExit}>
        ok
      </button>
    </div>
  );
}

// src/oceanpress-siyuan-plugin/ui/setting_view.vue
<template>
  <div class="content">
    选择 ocr api 提供程序：
    <select :value="selectedValue" @change="handleTypeChange" name="ocr type">
      <option value="oceanpress">oceanpress</option>
      <option value="umi-ocr">umi-ocr</option>
    </select>
    <div v-if="selectedValue === 'oceanpress'">
      sk
      <input
        type="text"
        class="input"
        placeholder="Enter sk..."
        :value="sk"
        @input="handleSkChange" />
    </div>
    <div v-if="selectedValue === 'umi-ocr'">
      http api
      <input
        type="text"
        class="input"
        placeholder="Enter http api ..."
        :value="umiApi"
        @input="handleUmiApiChange" />
    </div>
    <button class="button" @click="onExit">ok</button>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed } from 'vue';

  const props = defineProps({
    dialog: {
      type: Object,
      required: true,
    },
    dataSignal: {
      type: Object,
      required: true,
    },
    save: {
      type: Function,
      required: true,
    },
  });

  const data = ref(props.dataSignal);
  const selectedValue = computed(() => data.value.type);
  const sk = computed(() => data.value.sk);
  const umiApi = computed(() => data.value.umiApi);

  const onExit = () => {
    props.save();
    props.dialog.destroy();
  };

  const setData = (updater: (prev: any) => any) => {
    data.value = updater(data.value);
  };

  const handleTypeChange = (e: Event) => {
    setData((prev) => ({
      ...prev,
      type: (e.target as HTMLSelectElement).value as 'oceanpress',
    }));
  };

  const handleSkChange = (e: Event) => {
    setData((prev) => ({
      ...prev,
      sk: (e.target as HTMLInputElement).value,
    }));
  };

  const handleUmiApiChange = (e: Event) => {
    setData((prev) => ({
      ...prev,
      umiApi: (e.target as HTMLInputElement).value,
    }));
  };
</script>

<style scoped>
  /* 内容容器样式 */
  .content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 20px;
    background-color: white;
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    min-width: 400px;
  }

  /* 输入框样式 */
  .input {
    width: 100%;
    max-width: 300px;
    padding: 10px;
    margin-top: 15px;
    margin-bottom: 15px;
    border: 1px solid #ddd;
    border-radius: 4px;
  }

  /* 按钮样式 */
  .button {
    padding: 10px 20px;
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 4px;
    cursor: pointer;
    transition: background-color 0.3s;
  }
</style>
